"""add seat_templates table

Revision ID: 3107f0164732
Revises: d780c7fe3284
Create Date: 2026-03-21 12:19:57.176411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3107f0164732'
down_revision: Union[str, Sequence[str], None] = 'd780c7fe3284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seat_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_model_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_model_id'], ['aircrafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seat_templates')
    # ### end Alembic commands ###
