"""add flights table

Revision ID: b293b76d8ed5
Revises: 1a6301b44a93
Create Date: 2026-03-14 14:15:41.279775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b293b76d8ed5'
down_revision: Union[str, Sequence[str], None] = '1a6301b44a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=12), nullable=False),
    sa.Column('departure_airport_id', sa.Integer(), nullable=False),
    sa.Column('arrival_airport_id', sa.Integer(), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('departure_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], ),
    sa.ForeignKeyConstraint(['arrival_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['departure_airport_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flights_arrival_airport_id', 'flights', ['departure_airport_id'], unique=False)
    op.create_index('ix_flights_arrival_at', 'flights', ['arrival_at'], unique=False)
    op.create_index('ix_flights_departure_airport_id', 'flights', ['arrival_airport_id'], unique=False)
    op.create_index('ix_flights_departure_at', 'flights', ['departure_at'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flights_departure_at', table_name='flights')
    op.drop_index('ix_flights_departure_airport_id', table_name='flights')
    op.drop_index('ix_flights_arrival_at', table_name='flights')
    op.drop_index('ix_flights_arrival_airport_id', table_name='flights')
    op.drop_table('flights')
