"""add flight_instances table

Revision ID: 4d43848dcc78
Revises: 209fb8b5997e
Create Date: 2026-03-26 14:32:50.207076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d43848dcc78'
down_revision: Union[str, Sequence[str], None] = '209fb8b5997e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=12), nullable=False),
    sa.Column('seat_template_id', sa.Integer(), nullable=False),
    sa.Column('departure_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('departure_airport_id', sa.Integer(), nullable=False),
    sa.Column('arrival_airport_id', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'DELAYED', 'DEPARTED', 'ARRIVED', 'CANCELLED', name='flightstatus'), nullable=False),
    sa.ForeignKeyConstraint(['arrival_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['departure_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['seat_template_id'], ['seat_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flight_instances_arrival_at', 'flight_instances', ['arrival_at'], unique=False)
    op.create_index('ix_flight_instances_departure_airport_id', 'flight_instances', ['departure_airport_id'], unique=False)
    op.create_index('ix_flight_instances_departure_at', 'flight_instances', ['departure_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flight_instances_departure_at', table_name='flight_instances')
    op.drop_index('ix_flight_instances_departure_airport_id', table_name='flight_instances')
    op.drop_index('ix_flight_instances_arrival_at', table_name='flight_instances')
    op.drop_table('flight_instances')
    # ### end Alembic commands ###
